org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-26

org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.justnothing
archives_base_name=function-projectiles

# Fabric API
fabric_api_version=0.154.0+26.1.2

# Loom
loom_version=1.17-SNAPSHOT
